# Generated by Django 6.0.3 on 2026-03-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
