# Generated by Django 6.0.3 on 2026-03-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_profile_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pix',
        ),
    ]
